apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-05-27T15:44:14Z"
  generation: 1
  labels:
    app: my-nginx-deployment
  name: my-nginx-deployment
  namespace: default
  uid: 9947859e-085c-43ab-b700-a1dcf4ddac20
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx-deployment
    spec:
      containers:
      - image: nginx:1.17.0-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}